export const appList = [{
    url: "https://www.baidu.com",
    name: "百度",
    icon: "https://www.baidu.com/favicon.ico"
}, {
    url: "https://www.bilibili.com",
    name: "哔哩哔哩",
    icon: "https://www.bilibili.com/favicon.ico"
}, {
    url: "https://www.github.com",
    name: "GitHub",
    icon: "https://www.github.com/favicon.ico"
}, {
    url: "https://www.baidu.com",
    name: "百度",
    icon: "https://www.baidu.com/favicon.ico"
}, {
    url: "https://www.bilibili.com",
    name: "哔哩哔哩",
    icon: "https://www.bilibili.com/favicon.ico"
}, {
    url: "https://www.github.com",
    name: "GitHub",
    icon: "https://www.github.com/favicon.ico"
}, {
    url: "https://www.baidu.com",
    name: "百度",
    icon: "https://www.baidu.com/favicon.ico"
}, {
    url: "https://www.bilibili.com",
    name: "哔哩哔哩",
    icon: "https://www.bilibili.com/favicon.ico"
}, {
    url: "https://www.github.com",
    name: "GitHub",
    icon: "https://www.github.com/favicon.ico"
}, {
    url: "https://www.baidu.com",
    name: "百度",
    icon: "https://www.baidu.com/favicon.ico"
}, {
    url: "https://www.bilibili.com",
    name: "哔哩哔哩",
    icon: "https://www.bilibili.com/favicon.ico"
}, {
    url: "https://www.github.com",
    name: "GitHub",
    icon: "https://www.github.com/favicon.ico"
}, {
    url: "https://www.baidu.com",
    name: "百度",
    icon: "https://www.baidu.com/favicon.ico"
}, {
    url: "https://www.bilibili.com",
    name: "哔哩哔哩",
    icon: "https://www.bilibili.com/favicon.ico"
}, {
    url: "https://www.github.com",
    name: "GitHub",
    icon: "https://www.github.com/favicon.ico"
}, {
    url: "https://www.baidu.com",
    name: "百度",
    icon: "https://www.baidu.com/favicon.ico"
}, {
    url: "https://www.bilibili.com",
    name: "哔哩哔哩",
    icon: "https://www.bilibili.com/favicon.ico"
}, {
    url: "https://www.github.com",
    name: "GitHub",
    icon: "https://www.github.com/favicon.ico"
}, {
    url: "https://www.bilibili.com",
    name: "哔哩哔哩",
    icon: "https://www.bilibili.com/favicon.ico"
}, {
    url: "https://www.github.com",
    name: "GitHub",
    icon: "https://www.github.com/favicon.ico"
}, {
    url: "https://www.baidu.com",
    name: "百度",
    icon: "https://www.baidu.com/favicon.ico"
}, {
    url: "https://www.bilibili.com",
    name: "哔哩哔哩",
    icon: "https://www.bilibili.com/favicon.ico"
}, {
    url: "https://www.github.com",
    name: "GitHub",
    icon: "https://www.github.com/favicon.ico"
}];